// 메인 페이지 Weekly 베스트트 제품 데이터 정제
export const weeklyBestProducts = (rawData) => {
  return rawData.map(
    ({
      supplierId,
      brandId,
      brand,
      upCategoryId,
      upCategory,
      middleCategoryId,
      middleCategory,
      downCategoryId,
      downCategory,
      productId,
      productName,
      classificationCode,
      labelList,
      modelNumber,
      deliveryType,
      deliveryPrice,
      sellClassification,
      expressionCheck,
      sellPrice,
      normalPrice,
      eventStartDate,
      eventEndDate,
      eventDescription,
      optionCheck,
      productOptionList,
      mediaList,
      manufacturer,
      madeInOrigin,
      consignmentStore,
      memo,
      status,
    }) => {
      return {
        brand: brand,
        upCategory: upCategory,
        middleCategory: middleCategory,
        downCategory: downCategory,
        productId: productId,
        productName: productName,
        classificationCode: classificationCode,
        modelNumber: modelNumber,
        deliveryType: deliveryType,
        deliveryPrice: deliveryPrice,
        sellClassification: sellClassification,
        sellPrice: sellPrice,
        productOptionList: productOptionList,
        mediaList: mediaList,
        manufacturer: manufacturer,
        madeInOrigin: madeInOrigin,
        consignmentStore: consignmentStore,
      };
    }
  );
};

// 메인 페이지 카테고리 BEST 제품 데이터 정제
export const categoryBestProducts = (rawData) => {
  return rawData.map(
    ({
      supplierId,
      brandId,
      brand,
      upCategoryId,
      upCategory,
      middleCategoryId,
      middleCategory,
      downCategoryId,
      downCategory,
      productId,
      productName,
      classificationCode,
      labelList,
      modelNumber,
      deliveryType,
      deliveryPrice,
      sellClassification,
      expressionCheck,
      sellPrice,
      normalPrice,
      eventStartDate,
      eventEndDate,
      eventDescription,
      optionCheck,
      productOptionList,
      mediaList,
      manufacturer,
      madeInOrigin,
      consignmentStore,
      memo,
      status,
    }) => {
      return {
        brand: brand,
        upCategory: upCategory,
        middleCategory: middleCategory,
        downCategory: downCategory,
        productId: productId,
        productName: productName,
        classificationCode: classificationCode,
        modelNumber: modelNumber,
        deliveryType: deliveryType,
        deliveryPrice: deliveryPrice,
        sellClassification: sellClassification,
        sellPrice: sellPrice,
        productOptionList: productOptionList,
        mediaList: mediaList,
        manufacturer: manufacturer,
        madeInOrigin: madeInOrigin,
        consignmentStore: consignmentStore,
      };
    }
  );
};

// 메인 페이지 신 상품 제품 데이터 정제
export const newReleaseProducts = (rawData) => {
  return rawData.map(
    ({
      supplierId,
      brandId,
      brand,
      upCategoryId,
      upCategory,
      middleCategoryId,
      middleCategory,
      downCategoryId,
      downCategory,
      productId,
      productName,
      classificationCode,
      labelList,
      modelNumber,
      deliveryType,
      sellClassification,
      expressionCheck,
      normalPrice,
      sellPrice,
      deliveryPrice,
      purchasePrice,
      eventStartDate,
      eventEndDate,
      eventDescription,
      optionCheck,
      productOptionList,
      productDetailInfo,
      mediaList,
      manufacturer,
      madeInOrigin,
      consignmentStore,
      memo,
      status,
    }) => {
      return {
        brand: brand,
        upCategory: upCategory,
        middleCategory: middleCategory,
        downCategory: downCategory,
        productId: productId,
        productName: productName,
        classificationCode: classificationCode,
        modelNumber: modelNumber,
        deliveryType: deliveryType,
        deliveryPrice: deliveryPrice,
        sellClassification: sellClassification,
        sellPrice: sellPrice,
        productOptionList: productOptionList,
        mediaList: mediaList,
        manufacturer: manufacturer,
        madeInOrigin: madeInOrigin,
        consignmentStore: consignmentStore,
      };
    }
  );
};

// 대분류, 중분류, 소분류 카테고리 선택 시 호출되는 제품 리스트 데이터 정제
export const categorySelectProducts = (rawData) => {
  return rawData.map(
    ({
      supplierId,
      brandId,
      brand,
      upCategoryId,
      upCategory,
      middleCategoryId,
      middleCategory,
      downCategoryId,
      downCategory,
      productId,
      productName,
      classificationCode,
      labelList,
      modelNumber,
      deliveryType,
      sellClassification,
      expressionCheck,
      normalPrice,
      sellPrice,
      deliveryPrice,
      purchasePrice,
      eventStartDate,
      eventEndDate,
      eventDescription,
      optionCheck,
      productOptionList,
      productDetailInfo,
      mediaList,
      manufacturer,
      madeInOrigin,
      consignmentStore,
      memo,
      status,
    }) => {
      return {
        supplierId: supplierId,
        brandId: brandId,
        brand: brand,
        upCategoryId: upCategoryId,
        upCategory: upCategory,
        middleCategoryId: middleCategoryId,
        middleCategory: middleCategory,
        downCategoryId: downCategoryId,
        downCategory: downCategory,
        productId: productId,
        productName: productName,
        classificationCode: classificationCode,
        labelList: labelList,
        modelNumber: modelNumber,
        deliveryType: deliveryType,
        normalPrice: normalPrice,
        sellPrice: sellPrice,
        deliveryPrice: deliveryPrice,
        purchasePrice: purchasePrice,
        eventStartDate: eventStartDate,
        eventEndDate: eventEndDate,
        eventDescription: eventDescription,
        mediaList: mediaList,
      };
    }
  );
};
